# Generated by Django 5.0.6 on 2024-07-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_item_character_character_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='power',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='item',
            name='armor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='durability',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='item',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=10),
        ),
    ]
