# Generated by Django 5.0.6 on 2024-07-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_character_armor_character_hp_character_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
