# Generated by Django 5.0.6 on 2024-07-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_monster'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='default_hp',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='stamina',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='item',
            name='stamina',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='monster',
            name='stamina',
            field=models.IntegerField(default=5),
        ),
    ]
